# Windows and Linux build command: python setup.py build
# Build Microsoft installer command: python setup.py bdist_msi
# Build Linux installer command: python setup.py bdist_wheel


import cx_Freeze


cx_Freeze.setup(
    # the name of the exe file
    name="The Space Invader",
    options={
        "build_exe": {
            # the main mudule in my py file
            "packages": ["pygame"],
            # the mudules that cx_freeze will exclude from the lib file in build file and msi file
            "excludes": [
                "asttokens",
                "asyncio",
                "attr",
                "backcall",
                "black",
                "cffi",
                "charset_normalizer",
                "colorama",
                "comm",
                "concurrent",
                "ctypes",
                "curses",
                "cv2",
                "dateutil",
                "debugpy",
                "distutils",
                "email",
                "executing",
                "html",
                "http",
                "iniconfig",
                "ipykernel",
                "IPython",
                "jedi",
                "jinja2",
                "json",
                "jupyter_client",
                "jupyter_core",
                "lib2to3",
                "libcrypto-1_1.dll",
                "libffi-8.dll",
                "library.zip",
                "libssl-1_1.dll",
                "logging",
                "markupsafe",
                "matplotlib_inline",
                "multiprocessing",
                "numpy",
                "packaging",
                "parso",
                "PIL",
                "pkg_resources",
                "platformdirs",
                "pluggy",
                "prompt_toolkit",
                "psutil",
                "pure_eval",
                "pycparser",
                "pydoc_data",
                "pyexpat.pyd",
                "pygments",
                "PyQt5",
                "pytest",
                "pythoncom311.dll",
                "pywin32_system32",
                "pywintypes311.dll",
                "pyzmq.libs",
                "select.pyd",
                "setuptools",
                "sqlite3",
                "sqlite3.dll",
                "stack_data",
                "tcl8",
                "tcl8.6",
                "tcl86t.dll",
                "test",
                "tk8.6",
                "tk86t.dll",
                "tkinter",
                "tomllib",
                "tornado",
                "traitlets",
                "unicodedata.pyd",
                "unittest",
                "urllib",
                "wcwidth",
                "wheel",
                "win32api.pyd",
                "win32clipboard.pyd",
                "win32com",
                "win32evtlog.pyd",
                "win32file.pyd",
                "win32pdh.pyd",
                "win32pipe.pyd",
                "win32security.pyd",
                "xml",
                "xmlrpc",
                "zmq",
                "_asyncio.pyd",
                "_bz2.pyd",
                "_cffi_backend.cp311-win_amd64.pyd",
                "_ctypes.pyd",
                "_decimal.pyd",
                "_distutils_hack",
                "_elementtree.pyd",
                "_hashlib.pyd",
                "_lzma.pyd",
                "_multiprocessing.pyd",
                "_overlapped.pyd",
                "_pytest",
                "_queue.pyd",
                "_socket.pyd",
                "_sqlite3.pyd",
                "_ssl.pyd",
                "_testbuffer.pyd",
                "_testcapi.pyd",
                "_testinternalcapi.pyd",
                "_tkinter.pyd",
                "_uuid.pyd",
                "_win32sysloader.pyd",
                "__init__.cp311-win_amd64.pyd",
            ],
            "include_files": ["images", "tracks"],
        }
    },
    executables=[
        cx_Freeze.Executable(
            # the py file that will become exe file name
            script="project.py",
            # the exe file icon
            icon="images/gameicon.bmp",
            # base= "Win32GUI"
        )
    ],
)
